[client]
remote_addr = "94.182.145.210:27015"
default_token = "iJT5nWLo6fYI8zMxHPeDE7ok"
heartbeat_timeout = 0

[client.transport]
type = "noise"

[client.transport.noise]
pattern = "Noise_KK_25519_ChaChaPoly_BLAKE2s"
local_private_key = "CJHbyVBCnIFXW9zz4kTvrQQWJfo0257MDYpq0KqaPlI="
remote_public_key = "bnXjhbLKrzKR4gjTr+DdYlalu7mvqT/QQtCur6DEnyo="

[client.services.tcp]
local_addr = "0.0.0.0:42200"
type = "tcp"

[client.services.xray]
local_addr = "0.0.0.0:8081"
type = "tcp"
